name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]
                use-opcache: [true, false]

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none
                    ini-values: "session.save_path=/tmp"
                    tools: pecl
            - name: install dependencies
              run: sudo apt-get install -y libcurl4-openssl-dev
            - name: Compile
              run: ./.scripts/compile.sh
            - name: pull solr 5 image
              run: docker pull omars/solr53
            - name: spin up the solr docker container
              run: docker run -d --name solr53 -p 127.0.0.1:8983:8983 -t omars/solr53
            - name: test
              run: make test