name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]

jobs:
    tests:
        runs-on: ubuntu-latest
        name: Build and test
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4]
                use-opcache: [true, false]

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none
                    ini-values: "session.save_path=/tmp"
                    tools: pecl
            - name: install dependencies
              run: sudo apt-get install -y libcurl4-openssl-dev
            - name: Compile
              run: ./.build.scripts/compile.sh
                
