name: Build

on:
    push:
        branches: [master]
    pull_request:
    release:
        types: [created]

jobs:
    against-php-70:
        name: against-php-70
        env:
            PHP: "7.0"
            enable_debug: "yes"
            enable_maintainer_zts: "yes"
            enable_json: "yes"
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Install
              run: |
                  sudo apt-get install -y \
                    php-cli \
                    php-pear \
                    re2c
            - name: Prepare
              run: |
                  make -f .scripts/ci/Makefile php || make -f .scripts/ci/Makefile clean php
            - name: install dependencies
              run: sudo apt-get install -y libcurl4-openssl-dev
            - name: Compile
              run: ./.scripts/compile.sh
            - name: pull solr 5 image
              run: docker pull omars/solr53
            - name: wait for solr
              run: sleep 10
            - name: spin up the solr docker container
              run: docker run -d --name solr53 -p 127.0.0.1:8983:8983 -t omars/solr53
            - name: test
              run: PHP_TEST_SETTINGS=--show-diff make test
